name: Create Meeting Record issue
on:
  schedule:
    # 毎週金曜 13:00 JST
    - cron: '0 4 * * fri'
  # workflow_dispatch:
jobs:
  create_nippo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Create a new issue
        run: gh issue create --title "雑談会ログ - `date '+%Y/%m/%d'`" --body "今週の雑談会のログです:memo:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
